"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Modal from "@/components/Modal";
import { ModalStore } from "@/mobx/modalStore";
import { modals } from "@/util";
import { observer } from "mobx-react-lite";

// import url('https://fonts.googleapis.com/css2?family=Danfo&display=swap');

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "apartments-invest",
//   description: "Generated by Lee Yahav",
// };

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="body">
        <Header />

        <Modal
          bgColor="bg-white"
          isOpen={ModalStore.modalName === modals.scedule}
          closeModal={ModalStore.closeModal}
        >
          <div>soemthign</div>
        </Modal>

        <main className="mt-24 min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}

export default observer(RootLayout);
